name: layout
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imageUrls/kkulogo.png
    - assets/imageUrls/P.jpg
    - assets/imageUrls/kkulogo.png
    - assets/imageUrls/Puu.JPG
    - assets/imageUrls/Tin.jpg
    - assets/imageUrls/Big.jpg
    - assets/imageUrls/kkulogo.png
    - assets/imageUrls/Net.jpg
    - assets/imageUrls/kkulogo.png
    - assets/imageUrls/Ta.jpg
    - assets/imageUrls/fork.jpg
    - assets/imageUrls/PP.jpg
    - assets/imageUrls/Nu.jpg
    - assets/imageUrls/Zack.jpg
    - assets/imageUrls/kkulogo.png
    - assets/imageUrls/wichcapon.JPG
    - assets/imageUrls/Noey.JPG
    - assets/imageUrls/Mix.jpg
    - assets/imageUrls/Mo.jpg
    - assets/imageUrls/Ice.jpg
    - assets/imageUrls/Pu.png
    - assets/imageUrls/Piano.jpg
    - assets/imageUrls/mind.jpg
    - assets/imageUrls/Pun.jpg
    - assets/imageUrls/Terk.jpg
    - assets/imageUrls/Bam.JPG
    - assets/imageUrls/korn.JPG
    - assets/imageUrls/Icecy.jpg
    - assets/imageUrls/Boss.jpg
    - assets/imageUrls/Peach.jpg
    - assets/imageUrls/Not.jpg
    - assets/imageUrls/Gus.jpg
    - assets/imageUrls/Ger.jpg
    - assets/imageUrls/palm.jpg
    - assets/imageUrls/prajak.jpg
    - assets/imageUrls/Panu.jpg
    - assets/imageUrls/kkulogo.png
    - assets/imageUrls/Min.jpg
    - assets/imageUrls/dung.jpg
    - assets/imageUrls/dom.jpg
    - assets/imageUrls/Haroon.jpg
    - assets/imageUrls/kkulogo.png
    - assets/imageUrls/kkulogo.png
    - assets/imageUrls/Plem.jpg
    - assets/imageUrls/Mungkorn.jpg
    - assets/imageUrls/tal.png